- hosts: all
  tasks: 
  - yum_repository:
          baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
          name: "dkrrepo"
          description: "dce"
          gpgcheck: no

  - pip:
          name: "docker"
          state: present
 
          
  - service:

          name: "docker"
          state: started
  
   
  - name: Pull Image
    docker_image:
          name: harvinderosahan31/httpd-snake-game:v3
          source: pull
          state: present
 

  - name: Create a container
    docker_container:
          name: "SG1"
          image: harvinderosahan31/httpd-snake-game:v3
          state: started
          exposed_ports:
                  - "80"
          ports:
                  - "80:80"


